#!#/bin/bash
#based on http://techfunbln.blogspot.de/2013/09/raspberry-pi-als-openvpn-gateway-mit.html
#based on https://www.kadder.de/2013/12/raspberry-pi-als-vpn-gateway/
#based on https://www.expressvpn.com/support/vpn-setup/linux-openvpn-terminal/

# download: http://www.chip.de/downloads/Raspbian-Jessie-fuer-Raspberry-Pi_56691903.html
dd bs=1M if=...img of=/dev/sdb
# mount SDcard
# cp OVPN file to  /etc/openvpn
# boot RaspPi
sudo aptitude install openvpn
sudo openvpn --config /etc/openvpn/<expressVPN file>
# check wheter you see a tun0 interface using:
ifconfig

# GATEWAY:
echo 'AUTOSTART="standard"' >> /etc/default/openvpn
ln -s  /etc/openvpn/<expressVPN file>  /etc/openvpn/standard.conf
# add 
echo "script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf

redirect-gateway" >>  /etc/openvpn/standard.conf

#change name of box:
echo "vpn_gateway" > /etc/hostname
echo "127.0.0.1   vpn_gateway" > /etc/hosts

# add gateway interface
echo "auto eth0:1
    iface eth0:1 inet static
    address 192.168.1.254
    netmask 255.255.255.0
    network 192.168.1.0
    broadcast 192.168.1.255
    gateway 192.168.1.1
" >> /etc/network/interfaces

# enable forwarding:
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

#add gateway routing:
echo "# Generated by iptables-save v1.4.13 on Thu Sep 19 21:00:26 2013
*nat
:PREROUTING ACCEPT [96:5419]
:INPUT ACCEPT [3:234]
:OUTPUT ACCEPT [1:84]
:POSTROUTING ACCEPT [3:175]
-A POSTROUTING -o tun0 -j MASQUERADE
COMMIT7
# Completed on Thu Sep 19 21:00:26 2013
# Generated by iptables-save v1.4.13 on Thu Sep 19 21:00:26 2013
*filter
:INPUT ACCEPT [226346:297484094]
:FORWARD ACCEPT [348840:301802510]
:OUTPUT ACCEPT [129590:33041957]
-A FORWARD -i eth0:1 -o tun0 -j ACCEPT
-A FORWARD -i tun0 -o eth0:1 -j ACCEPT
COMMIT
# Completed on Thu Sep 19 21:00:26 2013" >> /etc/rulesiptables
touch /etc/network/if-pre-up.d/iptables
echo "#!/bin/bash" >> /etc/network/if-pre-up.d/iptables
echo "/sbin/iptables-restore < /etc/rulesiptables" >> /etc/network/if-pre-up.d/iptables
chmod +x /etc/network/if-pre-up.d/iptables

